import type {
  User, Company, PlatformSettings, WarehouseListing, WarehouseBooking,
  ServiceListing, ServiceJob, WorkerProfile, WorkerCertification,
  ShiftPost, ShiftApplication, ShiftAssignment, TimeEntry,
  Payment, Review, Dispute, Message, CompanyUser,
} from './types';

export const SEED_USERS: User[] = [
  { id: 'u1', email: 'admin@dock2door.ca', password: 'admin123', name: 'Admin User', role: 'Admin', companyId: null, status: 'Active', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'u2', email: 'customer@freshmart.ca', password: 'password', name: 'James Chen', role: 'Customer', companyId: 'c1', status: 'Active', createdAt: '2024-01-05T00:00:00Z' },
  { id: 'u3', email: 'provider@vandc.ca', password: 'password', name: 'Sarah Kim', role: 'WarehouseProvider', companyId: 'c2', status: 'Active', createdAt: '2024-01-06T00:00:00Z' },
  { id: 'u4', email: 'provider@richmond.ca', password: 'password', name: 'David Park', role: 'WarehouseProvider', companyId: 'c3', status: 'Active', createdAt: '2024-01-07T00:00:00Z' },
  { id: 'u5', email: 'service@deltadev.ca', password: 'password', name: 'Mike Torres', role: 'ServiceProvider', companyId: 'c5', status: 'Active', createdAt: '2024-01-08T00:00:00Z' },
  { id: 'u6', email: 'employer@deltalog.ca', password: 'password', name: 'Tom Wilson', role: 'Employer', companyId: 'c9', status: 'Active', createdAt: '2024-01-09T00:00:00Z' },
  { id: 'u7', email: 'worker.marcus@gmail.com', password: 'password', name: 'Marcus Chen', role: 'Worker', companyId: null, status: 'Active', createdAt: '2024-01-10T00:00:00Z' },
  { id: 'u8', email: 'worker.ana@gmail.com', password: 'password', name: 'Ana Rodriguez', role: 'Worker', companyId: null, status: 'Active', createdAt: '2024-01-11T00:00:00Z' },
  { id: 'u9', email: 'worker.kevin@gmail.com', password: 'password', name: 'Kevin Park', role: 'Worker', companyId: null, status: 'Active', createdAt: '2024-01-12T00:00:00Z' },
  { id: 'u10', email: 'worker.jenny@gmail.com', password: 'password', name: 'Jenny Liu', role: 'Worker', companyId: null, status: 'Active', createdAt: '2024-01-13T00:00:00Z' },
];

export const SEED_COMPANIES: Company[] = [
  { id: 'c1', name: 'FreshMart Groceries', type: 'Customer', address: '1200 Seymour St', city: 'Vancouver', status: 'Approved', createdAt: '2024-01-05T00:00:00Z' },
  { id: 'c2', name: 'Vancouver Distribution Center', type: 'WarehouseProvider', address: '8800 Bridgeport Rd', city: 'Vancouver', status: 'Approved', createdAt: '2024-01-06T00:00:00Z' },
  { id: 'c3', name: 'Richmond Cold Storage', type: 'WarehouseProvider', address: '12500 Vulcan Way', city: 'Richmond', status: 'Approved', createdAt: '2024-01-07T00:00:00Z' },
  { id: 'c4', name: 'Delta Frozen Depot', type: 'WarehouseProvider', address: '7400 72nd St', city: 'Delta', status: 'Approved', createdAt: '2024-01-07T00:00:00Z' },
  { id: 'c5', name: 'Delta Devanning Crew', type: 'ServiceProvider', address: '5600 Ladner Trunk Rd', city: 'Delta', status: 'Approved', createdAt: '2024-01-08T00:00:00Z' },
  { id: 'c6', name: 'Richmond Forklift Ops', type: 'ServiceProvider', address: '2800 Shell Rd', city: 'Richmond', status: 'Approved', createdAt: '2024-01-08T00:00:00Z' },
  { id: 'c7', name: 'Surrey Local Trucking', type: 'ServiceProvider', address: '9800 King George Blvd', city: 'Surrey', status: 'Approved', createdAt: '2024-01-08T00:00:00Z' },
  { id: 'c8', name: 'Surrey Warehouse Solutions', type: 'WarehouseProvider', address: '15500 104 Ave', city: 'Surrey', status: 'Approved', createdAt: '2024-01-09T00:00:00Z' },
  { id: 'c9', name: 'Delta Logistics Co', type: 'Employer', address: '6200 Tilbury Ave', city: 'Delta', status: 'Approved', createdAt: '2024-01-09T00:00:00Z' },
  { id: 'c10', name: 'Pacific Coast Importers', type: 'Customer', address: '3400 E Hastings St', city: 'Vancouver', status: 'PendingApproval', createdAt: '2024-02-01T00:00:00Z' },
];

export const SEED_COMPANY_USERS: CompanyUser[] = [
  { id: 'cu1', companyId: 'c1', userId: 'u2', companyRole: 'Owner', status: 'Active' },
  { id: 'cu2', companyId: 'c2', userId: 'u3', companyRole: 'Owner', status: 'Active' },
  { id: 'cu3', companyId: 'c3', userId: 'u4', companyRole: 'Owner', status: 'Active' },
  { id: 'cu4', companyId: 'c5', userId: 'u5', companyRole: 'Owner', status: 'Active' },
  { id: 'cu5', companyId: 'c9', userId: 'u6', companyRole: 'Owner', status: 'Active' },
];

export const SEED_PLATFORM_SETTINGS: PlatformSettings = {
  id: 'ps1',
  warehouseCommissionPercentage: 8,
  serviceCommissionPercentage: 20,
  labourCommissionPercentage: 15,
  handlingFeePerPalletDefault: 12,
  taxMode: 'GST+PST',
  updatedAt: '2024-01-01T00:00:00Z',
  updatedBy: 'u1',
};

export const SEED_WAREHOUSE_LISTINGS: WarehouseListing[] = [
  {
    id: 'wl1',
    companyId: 'c2',
    name: 'Vancouver Dry Storage',
    address: '8800 Bridgeport Rd',
    city: 'Vancouver',
    geoLat: 49.1966,
    geoLng: -123.1096,
    warehouseType: 'Dry',
    availablePalletCapacity: 500,
    minPallets: 10,
    maxPallets: 500,
    storageTerm: 'Monthly',
    storageRatePerPallet: 28,
    inboundHandlingFeePerPallet: 12,
    outboundHandlingFeePerPallet: 12,
    receivingHours: 'Mon–Fri 07:00–17:00',
    accessRestrictions: 'Appointment required',
    insuranceRequirements: 'Minimum $2M liability',
    notes: 'Ground-level loading, 30 dock doors, 28ft clearance',
    status: 'Available',
    photos: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
    createdAt: '2024-01-06T00:00:00Z',
  },
  {
    id: 'wl2',
    companyId: 'c3',
    name: 'Richmond Chill Hub',
    address: '12500 Vulcan Way',
    city: 'Richmond',
    geoLat: 49.1388,
    geoLng: -123.0697,
    warehouseType: 'Chill',
    availablePalletCapacity: 200,
    minPallets: 5,
    maxPallets: 200,
    storageTerm: 'Weekly',
    storageRatePerPallet: 42,
    inboundHandlingFeePerPallet: 15,
    outboundHandlingFeePerPallet: 15,
    receivingHours: 'Mon–Sat 06:00–18:00',
    accessRestrictions: 'Food-grade only',
    insuranceRequirements: 'Minimum $5M liability + cargo',
    notes: '0–4°C controlled, food-safe, HACCP certified',
    status: 'Available',
    photos: ['https://images.unsplash.com/photo-1553413077-190dd305871c?w=800'],
    createdAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'wl3',
    companyId: 'c4',
    name: 'Delta Frozen Depot',
    address: '7400 72nd St',
    city: 'Delta',
    geoLat: 49.0815,
    geoLng: -123.0547,
    warehouseType: 'Frozen',
    availablePalletCapacity: 150,
    minPallets: 5,
    maxPallets: 150,
    storageTerm: 'Monthly',
    storageRatePerPallet: 58,
    inboundHandlingFeePerPallet: 18,
    outboundHandlingFeePerPallet: 18,
    receivingHours: 'Mon–Fri 08:00–16:00',
    accessRestrictions: 'Frozen product only, –18°C',
    insuranceRequirements: 'Minimum $5M liability + temperature loss',
    notes: 'Blast freeze available, –18°C to –22°C',
    status: 'Available',
    photos: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
    createdAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'wl4',
    companyId: 'c8',
    name: 'Surrey Dry Solutions',
    address: '15500 104 Ave',
    city: 'Surrey',
    geoLat: 49.1896,
    geoLng: -122.8467,
    warehouseType: 'Dry',
    availablePalletCapacity: 300,
    minPallets: 20,
    maxPallets: 300,
    storageTerm: 'Monthly',
    storageRatePerPallet: 22,
    inboundHandlingFeePerPallet: 10,
    outboundHandlingFeePerPallet: 10,
    receivingHours: 'Mon–Fri 07:00–18:00',
    accessRestrictions: 'None',
    insuranceRequirements: 'Minimum $2M liability',
    notes: 'New facility, cross-dock capable, ample truck court',
    status: 'Available',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    createdAt: '2024-01-09T00:00:00Z',
  },
];

export const SEED_WAREHOUSE_BOOKINGS: WarehouseBooking[] = [
  {
    id: 'wb1',
    listingId: 'wl1',
    customerCompanyId: 'c1',
    palletsRequested: 50,
    startDate: '2025-03-01',
    endDate: '2025-03-31',
    handlingRequired: true,
    customerNotes: 'Mixed SKU pallets, need daily access',
    providerResponseNotes: 'Space confirmed. Gate code will be provided.',
    proposedPrice: 2200,
    counterOfferPrice: null,
    finalPrice: 2200,
    status: 'Confirmed',
    paymentStatus: 'Paid',
    createdAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 'wb2',
    listingId: 'wl2',
    customerCompanyId: 'c1',
    palletsRequested: 30,
    startDate: '2025-03-10',
    endDate: '2025-03-17',
    handlingRequired: true,
    customerNotes: 'Perishable produce, temp-sensitive',
    providerResponseNotes: '',
    proposedPrice: 1890,
    counterOfferPrice: 1750,
    finalPrice: null,
    status: 'CounterOffered',
    paymentStatus: 'Pending',
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'wb3',
    listingId: 'wl3',
    customerCompanyId: 'c1',
    palletsRequested: 20,
    startDate: '2025-04-01',
    endDate: '2025-04-30',
    handlingRequired: false,
    customerNotes: 'Frozen seafood',
    providerResponseNotes: '',
    proposedPrice: 1360,
    counterOfferPrice: null,
    finalPrice: null,
    status: 'Requested',
    paymentStatus: 'Pending',
    createdAt: '2025-03-02T00:00:00Z',
  },
];

export const SEED_SERVICE_LISTINGS: ServiceListing[] = [
  {
    id: 'sl1',
    companyId: 'c5',
    category: 'Devanning',
    coverageArea: ['Delta', 'Richmond', 'Surrey'],
    hourlyRate: 95,
    perJobRate: null,
    minimumHours: 4,
    certifications: 'WCB, WHMIS, forklift certified crew',
    status: 'Active',
    createdAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'sl2',
    companyId: 'c6',
    category: 'Forklift',
    coverageArea: ['Richmond', 'Vancouver', 'Burnaby'],
    hourlyRate: 110,
    perJobRate: 450,
    minimumHours: 3,
    certifications: 'BC Forklift Operator Certificate, WCB',
    status: 'Active',
    createdAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'sl3',
    companyId: 'c7',
    category: 'LocalTruck',
    coverageArea: ['Surrey', 'Langley', 'Abbotsford', 'Delta'],
    hourlyRate: 125,
    perJobRate: 350,
    minimumHours: 2,
    certifications: 'Class 1/3 drivers, CVSE compliant',
    status: 'Active',
    createdAt: '2024-01-08T00:00:00Z',
  },
];

export const SEED_SERVICE_JOBS: ServiceJob[] = [
  {
    id: 'sj1',
    serviceId: 'sl1',
    customerCompanyId: 'c1',
    locationAddress: '8800 Bridgeport Rd',
    locationCity: 'Richmond',
    dateTimeStart: '2025-03-05T08:00:00Z',
    durationHours: 6,
    notes: 'Devan 2 containers of produce',
    totalPrice: 570,
    status: 'Completed',
    paymentStatus: 'Paid',
    checkInTs: '2025-03-05T08:05:00Z',
    checkOutTs: '2025-03-05T14:10:00Z',
    customerConfirmed: true,
    createdAt: '2025-02-28T00:00:00Z',
  },
  {
    id: 'sj2',
    serviceId: 'sl2',
    customerCompanyId: 'c1',
    locationAddress: '12500 Vulcan Way',
    locationCity: 'Richmond',
    dateTimeStart: '2025-03-12T09:00:00Z',
    durationHours: 4,
    notes: 'Forklift needed for racking',
    totalPrice: 440,
    status: 'Scheduled',
    paymentStatus: 'Pending',
    checkInTs: null,
    checkOutTs: null,
    customerConfirmed: false,
    createdAt: '2025-03-01T00:00:00Z',
  },
];

export const SEED_WORKER_PROFILES: WorkerProfile[] = [
  { id: 'wp1', userId: 'u7', displayName: 'Marcus Chen', skills: ['General'], coverageCities: ['Vancouver', 'Burnaby', 'Richmond'], hourlyExpectation: 22, verified: true, status: 'Active', bio: 'Reliable general labour with 3 years warehouse experience.', createdAt: '2024-01-10T00:00:00Z' },
  { id: 'wp2', userId: 'u8', displayName: 'Ana Rodriguez', skills: ['Driver', 'General'], coverageCities: ['Surrey', 'Delta', 'Langley'], hourlyExpectation: 28, verified: true, status: 'Active', bio: 'Class 3 licensed driver, 5 years local delivery.', createdAt: '2024-01-11T00:00:00Z' },
  { id: 'wp3', userId: 'u9', displayName: 'Kevin Park', skills: ['Forklift', 'General'], coverageCities: ['Richmond', 'Vancouver', 'Delta'], hourlyExpectation: 32, verified: true, status: 'Active', bio: 'Certified forklift operator, counter-balance & reach truck.', createdAt: '2024-01-12T00:00:00Z' },
  { id: 'wp4', userId: 'u10', displayName: 'Jenny Liu', skills: ['HighReach', 'Forklift'], coverageCities: ['Burnaby', 'Coquitlam', 'Surrey'], hourlyExpectation: 35, verified: true, status: 'Active', bio: 'Certified high-reach operator, racking specialist.', createdAt: '2024-01-13T00:00:00Z' },
];

export const SEED_WORKER_CERTIFICATIONS: WorkerCertification[] = [
  { id: 'wc1', workerUserId: 'u9', type: 'Forklift', expiryDate: '2026-06-30', certificateFile: 'forklift-cert-kevin.pdf', adminApproved: true },
  { id: 'wc2', workerUserId: 'u10', type: 'HighReach', expiryDate: '2026-09-30', certificateFile: 'highreach-cert-jenny.pdf', adminApproved: true },
];

export const SEED_SHIFT_POSTS: ShiftPost[] = [
  {
    id: 'sp1',
    employerCompanyId: 'c9',
    title: 'General Labour – Container Unload',
    category: 'General',
    locationAddress: '6200 Tilbury Ave',
    locationCity: 'Delta',
    date: '2025-03-10',
    startTime: '07:00',
    endTime: '11:00',
    hourlyRate: 22,
    flatRate: null,
    minimumHours: 4,
    workersNeeded: 2,
    requirements: 'Safety boots, hi-vis vest required',
    notes: '2 containers to unload, heavy items',
    status: 'Posted',
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'sp2',
    employerCompanyId: 'c9',
    title: 'Forklift Operator – Racking',
    category: 'Forklift',
    locationAddress: '12500 Vulcan Way',
    locationCity: 'Richmond',
    date: '2025-03-11',
    startTime: '08:00',
    endTime: '13:00',
    hourlyRate: 32,
    flatRate: null,
    minimumHours: 5,
    workersNeeded: 1,
    requirements: 'Valid forklift certificate, counter-balance experience',
    notes: 'Stacking to 5-high rack',
    status: 'Posted',
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'sp3',
    employerCompanyId: 'c9',
    title: 'HighReach Operator – Inventory',
    category: 'HighReach',
    locationAddress: '15500 104 Ave',
    locationCity: 'Surrey',
    date: '2025-03-12',
    startTime: '09:00',
    endTime: '15:00',
    hourlyRate: 35,
    flatRate: null,
    minimumHours: 6,
    workersNeeded: 1,
    requirements: 'Valid HighReach certificate required',
    notes: 'Inventory cycle count, heights up to 40ft',
    status: 'Posted',
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'sp4',
    employerCompanyId: 'c9',
    title: 'Driver – Local Delivery Run',
    category: 'Driver',
    locationAddress: '8800 Bridgeport Rd',
    locationCity: 'Vancouver',
    date: '2025-03-13',
    startTime: '06:00',
    endTime: '09:00',
    hourlyRate: 28,
    flatRate: null,
    minimumHours: 3,
    workersNeeded: 1,
    requirements: 'Class 3 licence required',
    notes: 'Grocery distribution run, Lower Mainland',
    status: 'Filled',
    createdAt: '2025-03-01T00:00:00Z',
  },
];

export const SEED_SHIFT_APPLICATIONS: ShiftApplication[] = [
  { id: 'sa1', shiftId: 'sp1', workerUserId: 'u7', status: 'Applied', appliedAt: '2025-03-02T10:00:00Z' },
  { id: 'sa2', shiftId: 'sp1', workerUserId: 'u8', status: 'Applied', appliedAt: '2025-03-02T11:00:00Z' },
  { id: 'sa3', shiftId: 'sp2', workerUserId: 'u9', status: 'Accepted', appliedAt: '2025-03-02T09:00:00Z' },
  { id: 'sa4', shiftId: 'sp3', workerUserId: 'u10', status: 'Applied', appliedAt: '2025-03-03T08:00:00Z' },
  { id: 'sa5', shiftId: 'sp4', workerUserId: 'u8', status: 'Accepted', appliedAt: '2025-03-02T07:00:00Z' },
];

export const SEED_SHIFT_ASSIGNMENTS: ShiftAssignment[] = [
  { id: 'ass1', shiftId: 'sp2', workerUserId: 'u9', confirmedRate: 32, status: 'Scheduled', createdAt: '2025-03-03T00:00:00Z' },
  { id: 'ass2', shiftId: 'sp4', workerUserId: 'u8', confirmedRate: 28, status: 'Completed', createdAt: '2025-03-03T00:00:00Z' },
];

export const SEED_TIME_ENTRIES: TimeEntry[] = [
  { id: 'te1', assignmentId: 'ass2', startTimestamp: '2025-03-13T06:05:00Z', endTimestamp: '2025-03-13T09:10:00Z', employerConfirmedHours: 3, employerNotes: 'Great work, on time.' },
];

export const SEED_PAYMENTS: Payment[] = [
  { id: 'pay1', referenceType: 'WarehouseBooking', referenceId: 'wb1', grossAmount: 2200, commissionAmount: 176, netAmount: 2024, status: 'Paid', createdAt: '2025-02-20T00:00:00Z' },
  { id: 'pay2', referenceType: 'ServiceJob', referenceId: 'sj1', grossAmount: 570, commissionAmount: 114, netAmount: 456, status: 'Paid', createdAt: '2025-03-05T16:00:00Z' },
  { id: 'pay3', referenceType: 'ShiftAssignment', referenceId: 'ass2', grossAmount: 84, commissionAmount: 12.6, netAmount: 71.4, status: 'Paid', createdAt: '2025-03-13T12:00:00Z' },
];

export const SEED_REVIEWS: Review[] = [
  { id: 'rv1', type: 'WarehouseListing', reviewerUserId: 'u2', targetId: 'wl1', rating: 5, comment: 'Excellent facility, very organized staff.', relatedReferenceType: 'WarehouseBooking', relatedReferenceId: 'wb1', createdAt: '2025-03-31T00:00:00Z' },
  { id: 'rv2', type: 'ServiceProviderCompany', reviewerUserId: 'u2', targetId: 'c5', rating: 4, comment: 'Fast and professional devanning crew.', relatedReferenceType: 'ServiceJob', relatedReferenceId: 'sj1', createdAt: '2025-03-05T18:00:00Z' },
];

export const SEED_DISPUTES: Dispute[] = [
  { id: 'dis1', referenceType: 'ShiftAssignment', referenceId: 'ass1', openedByUserId: 'u9', description: 'Employer refused to confirm hours worked. I worked 5.5h but only 5h confirmed.', status: 'Open', outcome: null, adminNotes: '', createdAt: '2025-03-12T18:00:00Z' },
];

export const SEED_MESSAGES: Message[] = [
  { id: 'msg1', referenceType: 'WarehouseBooking', referenceId: 'wb2', senderUserId: 'u3', text: 'Hi, we can do $1,750 for the week — we have a slight capacity constraint.', createdAt: '2025-03-01T10:00:00Z' },
  { id: 'msg2', referenceType: 'WarehouseBooking', referenceId: 'wb2', senderUserId: 'u2', text: 'Thanks, let me check with my team and confirm.', createdAt: '2025-03-01T10:30:00Z' },
];
